name: Dummy workflow

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'src/**'
      - '.github/workflows/lint.yml'

jobs:
  run-dummy:
    name: Required processes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: echo "This is a dummy workflow."
