name: Format | Doc | Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/fmt-doc.yml'

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  run-oxfmt-typedoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - uses: actions/setup-node@v6
      - run: |
          npm uninstall -g yarn
          corepack enable
          corepack prepare yarn@4.9.2 --activate
          yarn install --immutable
          yarn format
      - uses: stefanzweifel/git-auto-commit-action@v7.0.0
        with:
          commit_message: 'style: Format code with Oxfmt'
      - run: yarn docs
      - uses: actions/upload-artifact@v4
        with:
          name: docs-build
          path: docs/

  deploy:
    needs: run-oxfmt-typedoc
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: docs-build
          path: docs/
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/'
      - uses: actions/deploy-pages@v4
        id: deployment
